CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(120) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'vendor',
    phone VARCHAR(20),
    company_name VARCHAR(150),
    business_type VARCHAR(100),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    INDEX idx_users_email (email),
    INDEX idx_users_role (role),
    CONSTRAINT chk_users_role CHECK (role IN ('vendor', 'admin'))
);

CREATE TABLE IF NOT EXISTS events (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    event_date DATETIME NOT NULL,
    location VARCHAR(200),
    venue VARCHAR(200),
    expected_attendees INT,
    vendor_fee DOUBLE NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'upcoming',
    created_by_admin_id INT NOT NULL,
    default_currency VARCHAR(10) NOT NULL DEFAULT 'USD',
    currency_options VARCHAR(120) NOT NULL DEFAULT 'USD',
    mpesa_number VARCHAR(40),
    paypal_account VARCHAR(120),
    zelle_account VARCHAR(120),
    card_instructions VARCHAR(255),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_events_date (event_date),
    INDEX idx_events_status (status),
    INDEX idx_events_admin_owner (created_by_admin_id),
    CONSTRAINT fk_events_admin_owner FOREIGN KEY (created_by_admin_id) REFERENCES users(id),
    CONSTRAINT chk_events_status CHECK (status IN ('upcoming', 'ongoing', 'completed', 'cancelled'))
);

CREATE TABLE IF NOT EXISTS vendor_applications (
    id INT AUTO_INCREMENT PRIMARY KEY,
    vendor_id INT NOT NULL,
    event_id INT NOT NULL,
    product_service VARCHAR(200) NOT NULL,
    booth_requirements TEXT,
    additional_notes TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    admin_notes TEXT,
    reviewed_at DATETIME,
    reviewed_by INT,
    applied_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_vendor_event (vendor_id, event_id),
    INDEX idx_vendor_applications_vendor (vendor_id),
    INDEX idx_vendor_applications_event (event_id),
    INDEX idx_vendor_applications_status (status),
    CONSTRAINT fk_vendor_applications_vendor FOREIGN KEY (vendor_id) REFERENCES users(id),
    CONSTRAINT fk_vendor_applications_event FOREIGN KEY (event_id) REFERENCES events(id),
    CONSTRAINT fk_vendor_applications_reviewer FOREIGN KEY (reviewed_by) REFERENCES users(id),
    CONSTRAINT chk_vendor_applications_status CHECK (status IN ('pending', 'approved', 'rejected', 'withdrawn'))
);

CREATE TABLE IF NOT EXISTS payments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    application_id INT NOT NULL,
    vendor_id INT NOT NULL,
    amount DOUBLE NOT NULL,
    payment_method VARCHAR(50),
    transaction_id VARCHAR(100) UNIQUE,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    currency VARCHAR(10) NOT NULL DEFAULT 'USD',
    pay_to VARCHAR(255),
    payment_date DATETIME,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    notes TEXT,
    INDEX idx_payments_vendor (vendor_id),
    INDEX idx_payments_application (application_id),
    INDEX idx_payments_status (status),
    CONSTRAINT fk_payments_application FOREIGN KEY (application_id) REFERENCES vendor_applications(id),
    CONSTRAINT fk_payments_vendor FOREIGN KEY (vendor_id) REFERENCES users(id),
    CONSTRAINT chk_payments_status CHECK (status IN ('pending', 'completed', 'failed', 'refunded'))
);
